#include "bolun/hal/lumia_device.h"

#define LUMIA_BASE_FEATURES (BOLUN_LUMIA_FEATURE_TOUCH | BOLUN_LUMIA_FEATURE_CAMERA)
#define LUMIA_FRONT_CAMERA (LUMIA_BASE_FEATURES | BOLUN_LUMIA_FEATURE_FRONT_CAMERA)
#define LUMIA_LTE (LUMIA_FRONT_CAMERA | BOLUN_LUMIA_FEATURE_LTE)
#define LUMIA_SENSOR_CORE (LUMIA_LTE | BOLUN_LUMIA_FEATURE_SENSOR_CORE)
#define LUMIA_FLAGSHIP (LUMIA_SENSOR_CORE | BOLUN_LUMIA_FEATURE_NFC | BOLUN_LUMIA_FEATURE_GLANCE_DISPLAY)
#define LUMIA_CONTINUUM (LUMIA_FLAGSHIP | BOLUN_LUMIA_FEATURE_CONTINUUM_CLASS)

static const BolunLumiaBoardProfile kLumiaProfiles[] = {
    {BOLUN_LUMIA_520, "Lumia 520", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 512U, LUMIA_BASE_FEATURES},
    {BOLUN_LUMIA_525, "Lumia 525", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 1024U, LUMIA_BASE_FEATURES},
    {BOLUN_LUMIA_530, "Lumia 530", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 480U, 854U, 512U, LUMIA_BASE_FEATURES},
    {BOLUN_LUMIA_532, "Lumia 532", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 1024U, LUMIA_FRONT_CAMERA},
    {BOLUN_LUMIA_535, "Lumia 535", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 540U, 960U, 1024U, LUMIA_FRONT_CAMERA},
    {BOLUN_LUMIA_540, "Lumia 540", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_FRONT_CAMERA},
    {BOLUN_LUMIA_550, "Lumia 550", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE},
    {BOLUN_LUMIA_620, "Lumia 620", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 512U, LUMIA_FRONT_CAMERA},
    {BOLUN_LUMIA_625, "Lumia 625", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 512U, LUMIA_LTE},
    {BOLUN_LUMIA_630, "Lumia 630", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 480U, 854U, 512U, LUMIA_BASE_FEATURES},
    {BOLUN_LUMIA_635, "Lumia 635", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 480U, 854U, 512U, LUMIA_LTE},
    {BOLUN_LUMIA_640, "Lumia 640", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE},
    {BOLUN_LUMIA_640_XL, "Lumia 640 XL", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE},
    {BOLUN_LUMIA_650, "Lumia 650", BOLUN_SOC_QUALCOMM_SNAPDRAGON_200, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE},
    {BOLUN_LUMIA_720, "Lumia 720", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 512U, LUMIA_FRONT_CAMERA | BOLUN_LUMIA_FEATURE_NFC},
    {BOLUN_LUMIA_730, "Lumia 730", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_FRONT_CAMERA},
    {BOLUN_LUMIA_735, "Lumia 735", BOLUN_SOC_QUALCOMM_SNAPDRAGON_400, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE | BOLUN_LUMIA_FEATURE_NFC},
    {BOLUN_LUMIA_820, "Lumia 820", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 480U, 800U, 1024U, LUMIA_LTE | BOLUN_LUMIA_FEATURE_NFC},
    {BOLUN_LUMIA_920, "Lumia 920", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 768U, 1280U, 1024U, LUMIA_FLAGSHIP},
    {BOLUN_LUMIA_925, "Lumia 925", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 768U, 1280U, 1024U, LUMIA_FLAGSHIP},
    {BOLUN_LUMIA_930, "Lumia 930", BOLUN_SOC_QUALCOMM_SNAPDRAGON_800, BOLUN_CPU_ARCH_AARCH32, 1080U, 1920U, 2048U, LUMIA_FLAGSHIP},
    {BOLUN_LUMIA_1020, "Lumia 1020", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 768U, 1280U, 2048U, LUMIA_FLAGSHIP},
    {BOLUN_LUMIA_1320, "Lumia 1320", BOLUN_SOC_QUALCOMM_SNAPDRAGON_S4, BOLUN_CPU_ARCH_AARCH32, 720U, 1280U, 1024U, LUMIA_LTE},
    {BOLUN_LUMIA_1520, "Lumia 1520", BOLUN_SOC_QUALCOMM_SNAPDRAGON_800, BOLUN_CPU_ARCH_AARCH32, 1080U, 1920U, 2048U, LUMIA_FLAGSHIP},
    {BOLUN_LUMIA_950, "Lumia 950", BOLUN_SOC_QUALCOMM_SNAPDRAGON_808, BOLUN_CPU_ARCH_AARCH64, 1440U, 2560U, 3072U, LUMIA_CONTINUUM},
    {BOLUN_LUMIA_950_XL, "Lumia 950 XL", BOLUN_SOC_QUALCOMM_SNAPDRAGON_810, BOLUN_CPU_ARCH_AARCH64, 1440U, 2560U, 3072U, LUMIA_CONTINUUM},
};

const BolunLumiaBoardProfile *BolunFindLumiaBoardProfile(BolunLumiaDeviceId id)
{
    for (size_t index = 0; index < (sizeof(kLumiaProfiles) / sizeof(kLumiaProfiles[0])); ++index) {
        if (kLumiaProfiles[index].id == id) {
            return &kLumiaProfiles[index];
        }
    }

    return NULL;
}

size_t BolunEnumerateLumiaBoardProfiles(const BolunLumiaBoardProfile **profiles, size_t capacity)
{
    const size_t count = sizeof(kLumiaProfiles) / sizeof(kLumiaProfiles[0]);
    const size_t copy_count = capacity < count ? capacity : count;

    if (profiles != NULL) {
        for (size_t index = 0; index < copy_count; ++index) {
            profiles[index] = &kLumiaProfiles[index];
        }
    }

    return count;
}

bool BolunLumiaHasFeature(const BolunLumiaBoardProfile *profile, BolunLumiaFeature feature)
{
    if (profile == NULL) {
        return false;
    }

    return (profile->features & (unsigned int)feature) != 0U;
}

BolunLumiaCompatibilityStatus BolunCheckLumiaCompatibility(const BolunLumiaBoardProfile *profile,
                                                           const BolunBootInfo *boot_info)
{
    if (profile == NULL || boot_info == NULL) {
        return BOLUN_LUMIA_UNSUPPORTED_DEVICE;
    }
    if (profile->soc_family != boot_info->soc_family || profile->cpu_architecture != boot_info->cpu_architecture) {
        return BOLUN_LUMIA_CPU_SOC_MISMATCH;
    }
    if (boot_info->framebuffer_width != 0U && boot_info->framebuffer_height != 0U &&
        (profile->display_width != boot_info->framebuffer_width || profile->display_height != boot_info->framebuffer_height)) {
        return BOLUN_LUMIA_DISPLAY_MISMATCH;
    }
    if (profile->ram_megabytes < 512U) {
        return BOLUN_LUMIA_INSUFFICIENT_RAM;
    }

    return BOLUN_LUMIA_COMPATIBLE;
}
